# Generated by Django 4.2.6 on 2023-10-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('Id_Calendario', models.AutoField(primary_key=True, serialize=False)),
                ('Calendario', models.CharField(db_column='Calendario', max_length=100)),
            ],
            options={
                'db_table': 'Calendario',
            },
        ),
        migrations.CreateModel(
            name='Colores',
            fields=[
                ('Id_Color', models.AutoField(primary_key=True, serialize=False)),
                ('Colores', models.CharField(db_column='Colores', max_length=100)),
            ],
            options={
                'db_table': 'Colores_Diseño',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('Id_Contacto', models.AutoField(primary_key=True, serialize=False)),
                ('Contacto', models.CharField(db_column='Contacto', max_length=100)),
            ],
            options={
                'db_table': 'Contacto',
            },
        ),
        migrations.CreateModel(
            name='Datos_Reserva',
            fields=[
                ('Id_DatosReserva', models.AutoField(primary_key=True, serialize=False)),
                ('Datos_Reserva', models.CharField(db_column='Datos', max_length=100)),
            ],
            options={
                'db_table': 'Datos_Reserva',
            },
        ),
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('Id_Dispositivos', models.AutoField(primary_key=True, serialize=False)),
                ('Dispositivos', models.CharField(db_column='Dispositivos', max_length=100)),
            ],
            options={
                'db_table': 'Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='Facilidad_Uso',
            fields=[
                ('Id_Facilidad', models.AutoField(primary_key=True, serialize=False)),
                ('Facilidad_Uso', models.CharField(db_column='Facilidades de Uso', max_length=100)),
            ],
            options={
                'db_table': 'Facilidad_Uso',
            },
        ),
        migrations.CreateModel(
            name='Funcionalidades',
            fields=[
                ('Id_Funcionalidades', models.AutoField(primary_key=True, serialize=False)),
                ('Funcionalidades', models.CharField(db_column='Funcionalidades', max_length=100)),
            ],
            options={
                'db_table': 'Funcionalidades',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('Id_idioma', models.AutoField(primary_key=True, serialize=False)),
                ('Idioma', models.CharField(db_column='Idiomas', max_length=100)),
            ],
            options={
                'db_table': 'Idioma',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('Id_Pago', models.AutoField(primary_key=True, serialize=False)),
                ('Pagos', models.CharField(db_column='Pagos', max_length=100)),
            ],
            options={
                'db_table': 'Pago',
            },
        ),
        migrations.CreateModel(
            name='Proceso_Reserva',
            fields=[
                ('Id_ProcesoReserva', models.AutoField(primary_key=True, serialize=False)),
                ('Proceso_Reserva', models.CharField(db_column='Proceso Reserva', max_length=100)),
            ],
            options={
                'db_table': 'Proceso_Reserva',
            },
        ),
        migrations.CreateModel(
            name='Redes',
            fields=[
                ('Id_Redes', models.AutoField(primary_key=True, serialize=False)),
                ('Redes_Sociales', models.CharField(db_column='Redes', max_length=100)),
            ],
            options={
                'db_table': 'Redes',
            },
        ),
        migrations.CreateModel(
            name='ServcioHotel',
            fields=[
                ('Id_Servicio', models.AutoField(primary_key=True, serialize=False)),
                ('Servicios', models.CharField(db_column='Servicios', max_length=100)),
            ],
            options={
                'db_table': 'Servicio_Hotel',
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('Id_TipoHabitacion', models.AutoField(primary_key=True, serialize=False)),
                ('Habitacion', models.CharField(db_column='Habitacion', max_length=100)),
            ],
            options={
                'db_table': 'Tipo_Habitacion',
            },
        ),
    ]
