# Generated by Django 4.2.6 on 2023-10-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('idRegistro', models.IntegerField(db_column='idRegistro', primary_key=True, serialize=False)),
                ('usuario', models.CharField(db_column='usuario', max_length=100)),
                ('correo', models.EmailField(db_column='correo', max_length=254)),
                ('password', models.CharField(db_column='password', max_length=100)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
    ]
